networks:
  akka-network:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
services:
  seed:
    image: "crush:0.1"
    entrypoint: "/opt/docker/bin/main"
    command: "root 24"
    environment:
      CLUSTER_IP: 172.18.0.20
      CLUSTER_PORT: 25520
      CLUSTER_SEED_IP: 172.18.0.20
    networks:
      akka-network:
        ipv4_address: 172.18.0.20


  osd1:
    depends_on: [seed]
    tty: false
    image: "crush:0.1"
    entrypoint: "/opt/docker/bin/main"
    command: "osd 0 10"
    environment:
        CLUSTER_IP: ${CLUSTER_IP:-172.18.0.21}
        CLUSTER_PORT: 25525
        CLUSTER_SEED_IP: 172.18.0.20
    networks:
    akka-network:
        ipv4_address: ${CLUSTER_IP:-172.18.0.21}



  osd2:
    depends_on: [seed]
    tty: false
    image: "crush:0.1"
    entrypoint: "/opt/docker/bin/main"
    command: "osd 1 10"
    environment:
        CLUSTER_IP: ${CLUSTER_IP:-172.18.0.22}
        CLUSTER_PORT: 25525
        CLUSTER_SEED_IP: 172.18.0.20
    networks:
    akka-network:
        ipv4_address: ${CLUSTER_IP:-172.18.0.22}



  osd3:
    depends_on: [seed]
    tty: false
    image: "crush:0.1"
    entrypoint: "/opt/docker/bin/main"
    command: "osd 2 10"
    environment:
        CLUSTER_IP: ${CLUSTER_IP:-172.18.0.23}
        CLUSTER_PORT: 25525
        CLUSTER_SEED_IP: 172.18.0.20
    networks:
    akka-network:
        ipv4_address: ${CLUSTER_IP:-172.18.0.23}



  osd4:
    depends_on: [seed]
    tty: false
    image: "crush:0.1"
    entrypoint: "/opt/docker/bin/main"
    command: "osd 3 10"
    environment:
        CLUSTER_IP: ${CLUSTER_IP:-172.18.0.24}
        CLUSTER_PORT: 25525
        CLUSTER_SEED_IP: 172.18.0.20
    networks:
    akka-network:
        ipv4_address: ${CLUSTER_IP:-172.18.0.24}



  osd5:
    depends_on: [seed]
    tty: false
    image: "crush:0.1"
    entrypoint: "/opt/docker/bin/main"
    command: "osd 4 10"
    environment:
        CLUSTER_IP: ${CLUSTER_IP:-172.18.0.25}
        CLUSTER_PORT: 25525
        CLUSTER_SEED_IP: 172.18.0.20
    networks:
    akka-network:
        ipv4_address: ${CLUSTER_IP:-172.18.0.25}



  osd6:
    depends_on: [seed]
    tty: false
    image: "crush:0.1"
    entrypoint: "/opt/docker/bin/main"
    command: "osd 5 10"
    environment:
        CLUSTER_IP: ${CLUSTER_IP:-172.18.0.26}
        CLUSTER_PORT: 25525
        CLUSTER_SEED_IP: 172.18.0.20
    networks:
    akka-network:
        ipv4_address: ${CLUSTER_IP:-172.18.0.26}



  osd7:
    depends_on: [seed]
    tty: false
    image: "crush:0.1"
    entrypoint: "/opt/docker/bin/main"
    command: "osd 6 10"
    environment:
        CLUSTER_IP: ${CLUSTER_IP:-172.18.0.27}
        CLUSTER_PORT: 25525
        CLUSTER_SEED_IP: 172.18.0.20
    networks:
    akka-network:
        ipv4_address: ${CLUSTER_IP:-172.18.0.27}



  osd8:
    depends_on: [seed]
    tty: false
    image: "crush:0.1"
    entrypoint: "/opt/docker/bin/main"
    command: "osd 7 10"
    environment:
        CLUSTER_IP: ${CLUSTER_IP:-172.18.0.28}
        CLUSTER_PORT: 25525
        CLUSTER_SEED_IP: 172.18.0.20
    networks:
    akka-network:
        ipv4_address: ${CLUSTER_IP:-172.18.0.28}



  osd9:
    depends_on: [seed]
    tty: false
    image: "crush:0.1"
    entrypoint: "/opt/docker/bin/main"
    command: "osd 8 10"
    environment:
        CLUSTER_IP: ${CLUSTER_IP:-172.18.0.29}
        CLUSTER_PORT: 25525
        CLUSTER_SEED_IP: 172.18.0.20
    networks:
    akka-network:
        ipv4_address: ${CLUSTER_IP:-172.18.0.29}



  osd10:
    depends_on: [seed]
    tty: false
    image: "crush:0.1"
    entrypoint: "/opt/docker/bin/main"
    command: "osd 9 10"
    environment:
        CLUSTER_IP: ${CLUSTER_IP:-172.18.0.30}
        CLUSTER_PORT: 25525
        CLUSTER_SEED_IP: 172.18.0.20
    networks:
    akka-network:
        ipv4_address: ${CLUSTER_IP:-172.18.0.30}



  osd11:
    depends_on: [seed]
    tty: false
    image: "crush:0.1"
    entrypoint: "/opt/docker/bin/main"
    command: "osd 10 10"
    environment:
        CLUSTER_IP: ${CLUSTER_IP:-172.18.0.31}
        CLUSTER_PORT: 25525
        CLUSTER_SEED_IP: 172.18.0.20
    networks:
    akka-network:
        ipv4_address: ${CLUSTER_IP:-172.18.0.31}



  osd12:
    depends_on: [seed]
    tty: false
    image: "crush:0.1"
    entrypoint: "/opt/docker/bin/main"
    command: "osd 11 10"
    environment:
        CLUSTER_IP: ${CLUSTER_IP:-172.18.0.32}
        CLUSTER_PORT: 25525
        CLUSTER_SEED_IP: 172.18.0.20
    networks:
    akka-network:
        ipv4_address: ${CLUSTER_IP:-172.18.0.32}



  osd13:
    depends_on: [seed]
    tty: false
    image: "crush:0.1"
    entrypoint: "/opt/docker/bin/main"
    command: "osd 12 10"
    environment:
        CLUSTER_IP: ${CLUSTER_IP:-172.18.0.33}
        CLUSTER_PORT: 25525
        CLUSTER_SEED_IP: 172.18.0.20
    networks:
    akka-network:
        ipv4_address: ${CLUSTER_IP:-172.18.0.33}



  osd14:
    depends_on: [seed]
    tty: false
    image: "crush:0.1"
    entrypoint: "/opt/docker/bin/main"
    command: "osd 13 10"
    environment:
        CLUSTER_IP: ${CLUSTER_IP:-172.18.0.34}
        CLUSTER_PORT: 25525
        CLUSTER_SEED_IP: 172.18.0.20
    networks:
    akka-network:
        ipv4_address: ${CLUSTER_IP:-172.18.0.34}



  osd15:
    depends_on: [seed]
    tty: false
    image: "crush:0.1"
    entrypoint: "/opt/docker/bin/main"
    command: "osd 14 10"
    environment:
        CLUSTER_IP: ${CLUSTER_IP:-172.18.0.35}
        CLUSTER_PORT: 25525
        CLUSTER_SEED_IP: 172.18.0.20
    networks:
    akka-network:
        ipv4_address: ${CLUSTER_IP:-172.18.0.35}



  osd16:
    depends_on: [seed]
    tty: false
    image: "crush:0.1"
    entrypoint: "/opt/docker/bin/main"
    command: "osd 15 10"
    environment:
        CLUSTER_IP: ${CLUSTER_IP:-172.18.0.36}
        CLUSTER_PORT: 25525
        CLUSTER_SEED_IP: 172.18.0.20
    networks:
    akka-network:
        ipv4_address: ${CLUSTER_IP:-172.18.0.36}



  osd17:
    depends_on: [seed]
    tty: false
    image: "crush:0.1"
    entrypoint: "/opt/docker/bin/main"
    command: "osd 16 10"
    environment:
        CLUSTER_IP: ${CLUSTER_IP:-172.18.0.37}
        CLUSTER_PORT: 25525
        CLUSTER_SEED_IP: 172.18.0.20
    networks:
    akka-network:
        ipv4_address: ${CLUSTER_IP:-172.18.0.37}



  osd18:
    depends_on: [seed]
    tty: false
    image: "crush:0.1"
    entrypoint: "/opt/docker/bin/main"
    command: "osd 17 10"
    environment:
        CLUSTER_IP: ${CLUSTER_IP:-172.18.0.38}
        CLUSTER_PORT: 25525
        CLUSTER_SEED_IP: 172.18.0.20
    networks:
    akka-network:
        ipv4_address: ${CLUSTER_IP:-172.18.0.38}



  osd19:
    depends_on: [seed]
    tty: false
    image: "crush:0.1"
    entrypoint: "/opt/docker/bin/main"
    command: "osd 18 10"
    environment:
        CLUSTER_IP: ${CLUSTER_IP:-172.18.0.39}
        CLUSTER_PORT: 25525
        CLUSTER_SEED_IP: 172.18.0.20
    networks:
    akka-network:
        ipv4_address: ${CLUSTER_IP:-172.18.0.39}



  osd20:
    depends_on: [seed]
    tty: false
    image: "crush:0.1"
    entrypoint: "/opt/docker/bin/main"
    command: "osd 19 10"
    environment:
        CLUSTER_IP: ${CLUSTER_IP:-172.18.0.40}
        CLUSTER_PORT: 25525
        CLUSTER_SEED_IP: 172.18.0.20
    networks:
    akka-network:
        ipv4_address: ${CLUSTER_IP:-172.18.0.40}



  osd21:
    depends_on: [seed]
    tty: false
    image: "crush:0.1"
    entrypoint: "/opt/docker/bin/main"
    command: "osd 20 10"
    environment:
        CLUSTER_IP: ${CLUSTER_IP:-172.18.0.41}
        CLUSTER_PORT: 25525
        CLUSTER_SEED_IP: 172.18.0.20
    networks:
    akka-network:
        ipv4_address: ${CLUSTER_IP:-172.18.0.41}



  osd22:
    depends_on: [seed]
    tty: false
    image: "crush:0.1"
    entrypoint: "/opt/docker/bin/main"
    command: "osd 21 10"
    environment:
        CLUSTER_IP: ${CLUSTER_IP:-172.18.0.42}
        CLUSTER_PORT: 25525
        CLUSTER_SEED_IP: 172.18.0.20
    networks:
    akka-network:
        ipv4_address: ${CLUSTER_IP:-172.18.0.42}



  osd23:
    depends_on: [seed]
    tty: false
    image: "crush:0.1"
    entrypoint: "/opt/docker/bin/main"
    command: "osd 22 10"
    environment:
        CLUSTER_IP: ${CLUSTER_IP:-172.18.0.43}
        CLUSTER_PORT: 25525
        CLUSTER_SEED_IP: 172.18.0.20
    networks:
    akka-network:
        ipv4_address: ${CLUSTER_IP:-172.18.0.43}



  osd24:
    depends_on: [seed]
    tty: false
    image: "crush:0.1"
    entrypoint: "/opt/docker/bin/main"
    command: "osd 23 10"
    environment:
        CLUSTER_IP: ${CLUSTER_IP:-172.18.0.44}
        CLUSTER_PORT: 25525
        CLUSTER_SEED_IP: 172.18.0.20
    networks:
    akka-network:
        ipv4_address: ${CLUSTER_IP:-172.18.0.44}



