networks:
  akka-network:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
services:
  seed:
    image: "crush:0.1"
    entrypoint: "/opt/docker/bin/main"
    command: _ROOTCOMMAND_
    environment:
      CLUSTER_IP: 172.18.0.20
      CLUSTER_PORT: 25520
      CLUSTER_SEED_IP: 172.18.0.20
    networks:
      akka-network:
        ipv4_address: 172.18.0.20

_OSDS_

