kind: Service
apiVersion: v1
metadata:
  name: crdt-graph
spec:
  type: LoadBalancer
  selector:
    app: crdt-graph
  ports:
  - protocol: TCP
    name: management
    port: 8558
    targetPort: management
  - protocol: TCP
    name: api
    port: 8080
    targetPort: api