apiVersion: v1
kind: ServiceAccount
metadata:
  name:  crdt-graph
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: crdt-graph
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: crdt-graph
subjects:
- kind: ServiceAccount
  name:  crdt-graph
  namespace: default
roleRef:
  kind: ClusterRole
  name: crdt-graph
  apiGroup: rbac.authorization.k8s.io